# Generated by Django 5.2.7 on 2025-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
