# Generated by Django 5.2.7 on 2025-12-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('visitors', '0003_add_company_contact_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateentry',
            options={'ordering': ['-entry_time'], 'verbose_name_plural': 'Gate Entries'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-check_in_time']},
        ),
        migrations.RenameField(
            model_name='gateentry',
            old_name='check_out_time',
            new_name='exit_time',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='host',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='gateentry',
            name='status',
        ),
        migrations.AddField(
            model_name='gateentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_entries', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='entry_type',
            field=models.CharField(choices=[('VISITOR', 'Visitor'), ('EMPLOYEE', 'Employee'), ('VENDOR', 'Vendor')], default='VISITOR', max_length=20),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='gate_number',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parking_slot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='host_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitors', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='id_proof_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('NATIONAL_ID', 'National ID'), ('OTHER', 'Other')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_of_visit',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_entries', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
