# Generated by Django 5.2.7 on 2025-11-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatarUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
