# Generated by Django 6.0.2 on 2026-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafm', '0003_asset_asset_id_asset_asset_value_asset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='location_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='work_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
