# Generated by Django 6.0.2 on 2026-03-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafm', '0004_maintenancerequest_estimated_completion_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('HVAC', 'HVAC System'), ('LIGHTING', 'Lighting Control'), ('ENERGY', 'Energy Meter'), ('SECURITY', 'Security System'), ('FIRE', 'Fire Alarm')], max_length=50)),
                ('external_id', models.CharField(help_text='ID from the BMS system', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_device', to='cafm.asset')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms_devices', to='cafm.facility')),
            ],
        ),
        migrations.CreateModel(
            name='BMSTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(help_text='e.g., Temperature, Power, Status', max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='cafm.bmsdevice')),
            ],
            options={
                'verbose_name_plural': 'BMS Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
