# Generated by Django 6.0.2 on 2026-03-14 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafm', '0007_cafmauditlog_maintenancecommunication'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('response_time_hours', models.IntegerField(help_text='Target response time in hours')),
                ('resolution_time_hours', models.IntegerField(help_text='Target resolution time in hours')),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('service_type', models.CharField(help_text='e.g., HVAC, Electrical, Plumbing', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_value',
            new_name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vendor_information',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='estimated_completion_time',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='location_details',
        ),
        migrations.AddField(
            model_name='asset',
            name='expected_life_years',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_logs/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(choices=[('REACTIVE', 'Reactive Maintenance'), ('PPM', 'Planned Preventive Maintenance'), ('EMERGENCY', 'Emergency'), ('INSPECTION', 'Inspection')], default='REACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bmsdevice',
            name='device_type',
            field=models.CharField(choices=[('HVAC', 'HVAC System'), ('LIGHTING', 'Lighting Control'), ('ENERGY', 'Energy Meter'), ('SECURITY', 'Security System'), ('FIRE', 'Fire Alarm'), ('WATER', 'Water Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bmsdevice',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bmstelemetry',
            name='reading_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ppmschedule',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='audit_type',
            field=models.CharField(choices=[('ASSET', 'Asset Integrity'), ('SAFETY', 'Health & Safety'), ('ENERGY', 'Energy Audit'), ('BMS', 'BMS Calibration'), ('COMPLIANCE', 'Regulatory Compliance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=5)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='cafm.asset')),
            ],
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafm.slapolicy'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafm.slapolicy'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='cafm.vendor'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work', to='cafm.vendor'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafm.vendor'),
        ),
        migrations.CreateModel(
            name='WorkOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cafm.maintenancerequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
