# Generated by Django 5.2.7 on 2025-12-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('OTHER', 'Other')], default='WEBSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('VIDEO', 'Video'), ('IN_PERSON', 'In-person'), ('TECHNICAL', 'Technical'), ('HR', 'HR Round')], default='VIDEO', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, help_text='Location or meeting link', max_length=200),
        ),
        migrations.AddField(
            model_name='interview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('STRONG_HIRE', 'Strong Hire'), ('HIRE', 'Hire'), ('MAYBE', 'Maybe'), ('NO_HIRE', 'No Hire')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('EXECUTIVE', 'Executive')], default='MID', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='Office', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='remote_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidateStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='recruitment.candidate')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.hiringstage')),
            ],
            options={
                'verbose_name_plural': 'Candidate Stage Histories',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruitment.hiringstage'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='recruitment.jobcategory'),
        ),
    ]
