# Generated by Django 5.2.7 on 2025-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_hiringstage_jobcategory_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
