# Generated by Django 5.2.7 on 2025-12-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('client_type', models.CharField(choices=[('ENTERPRISE', 'Enterprise'), ('SME', 'Small/Medium Enterprise'), ('GOVERNMENT', 'Government Entity'), ('NGO', 'Non-Governmental Organization'), ('INDIVIDUAL', 'Individual')], default='ENTERPRISE', max_length=20)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('NEGOTIATION', 'Negotiation'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / PAN')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='VAT / GST Registration')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. Net 30, Due on Receipt', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='employees.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('HEADQUARTERS', 'Headquarters'), ('BRANCH', 'Branch Office'), ('WAREHOUSE', 'Warehouse'), ('ONSITE_CLIENT', 'Client On-site Location'), ('OTHER', 'Other')], default='BRANCH', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('is_billing_address', models.BooleanField(default=False)),
                ('is_shipping_address', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='clients.client')),
            ],
        ),
    ]
