# Generated by Django 5.2.7 on 2025-12-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('strengths', models.TextField(blank=True, help_text='SWOT: Strengths')),
                ('weaknesses', models.TextField(blank=True, help_text='SWOT: Weaknesses')),
                ('opportunities', models.TextField(blank=True, help_text='SWOT: Opportunities')),
                ('threats', models.TextField(blank=True, help_text='SWOT: Threats')),
                ('market_trends', models.TextField(blank=True)),
                ('competitor_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marketing Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kpis', models.TextField(blank=True, help_text='Key Performance Indicators')),
                ('metrics_achieved', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='marketing.marketingplan')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_audience', models.TextField()),
                ('value_proposition', models.TextField()),
                ('key_channels', models.TextField(help_text='Primary marketing channels (e.g. SEO, Content, Social)')),
                ('objectives', models.TextField(help_text='Strategic objectives and goals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='marketing.marketinganalysis')),
            ],
            options={
                'verbose_name_plural': 'Marketing Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='marketing.marketingstrategy'),
        ),
    ]
