# Generated by Django 6.0.2 on 2026-03-16 19:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='metrics_achieved',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketinganalysis',
            name='opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketinganalysis',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketinganalysis',
            name='threats',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketinganalysis',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='budget_allocated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='kpis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='platform',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Twitter / X', 'Twitter / X'), ('Google Ads', 'Google Ads'), ('Email', 'Email Marketing'), ('YouTube', 'YouTube'), ('WhatsApp', 'WhatsApp'), ('Content / Blog', 'Content / Blog'), ('Events', 'Events & Webinars'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketingstrategy',
            name='key_channels',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marketingstrategy',
            name='objectives',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Social Media', 'Social Media'), ('Email', 'Email Campaign'), ('Referral', 'Referral'), ('Event', 'Event / Webinar'), ('Cold Outreach', 'Cold Outreach'), ('Other', 'Other')], default='Website', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.marketingcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
