# Generated by Django 6.0.2 on 2026-03-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('support', '0002_supportticket_asset_supportticket_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='employees.department'),
        ),
        migrations.CreateModel(
            name='EscalationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1 - Support Executive'), (2, 'Level 2 - Team Lead / Supervisor'), (3, 'Level 3 - Manager / HOD')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='employees.department')),
            ],
            options={
                'verbose_name_plural': 'Escalation Matrices',
                'ordering': ['department', 'level'],
            },
        ),
    ]
